[package]
name = "infoscreeen"
version = "0.1.0"
edition = "2024"
rust-version = "1.96.0"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_derive = "1.0.218"
axum = "0.8.9"
tokio = { version = "1.52.3", features = ["full"] }
log = "0.4.32"
log4rs = { version = "1.3.0", features = ["json_encoder"] }
reqwest = { version = "0.12.23", features = ["json"] }
chrono = { version = "0.4.41", features = ["serde"] }

[dev-dependencies]
