[package]
name = "infoscreeen"
version = "0.1.0"
edition = "2024"
rust-version = "1.96.0"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
axum = "0.8.9"
tokio = { version = "1.53.1", features = ["full"] }
log = "0.4.34"
log4rs = { version = "1.4.0", features = ["json_encoder"] }
reqwest = { version = "0.13.5", features = ["form", "json", "query"] }
chrono = { version = "0.4.45", features = ["serde"] }